const barData = [
           {
             value: 40,
             label: 'Jan',
              spacing: 2,
              labelWidth: 30,
              labelTextStyle: {color: 'gray'},
              frontColor: '#177AD5',
            },
            {value: 20, frontColor: '#ED6665'},
            {
              value: 50,
              label: 'Feb',
              spacing: 2,
              labelWidth: 30,
              labelTextStyle: {color: 'gray'},
              frontColor: '#177AD5',
            },
            {value: 40, frontColor: '#ED6665'},
            {
              value: 75,
              label: 'Mar',
              spacing: 2,
              labelWidth: 30,
              labelTextStyle: {color: 'gray'},
              frontColor: '#177AD5',
            },
            {value: 25, frontColor: '#ED6665'},
            {
              value: 30,
              label: 'Apr',
              spacing: 2,
              labelWidth: 30,
              labelTextStyle: {color: 'gray'},
              frontColor: '#177AD5',
            },
            {value: 20, frontColor: '#ED6665'},
            {
              value: 60,
              label: 'May',
              spacing: 2,
              labelWidth: 30,
              labelTextStyle: {color: 'gray'},
              frontColor: '#177AD5',
            },
            {value: 40, frontColor: '#ED6665'},
            {
              value: 65,
              label: 'Jun',
              spacing: 2,
              labelWidth: 30,
              labelTextStyle: {color: 'gray'},
              frontColor: '#177AD5',
            },
            {value: 30, frontColor: '#ED6665'},
            {
              value: 65,
              label: 'Jul',
              spacing: 2,
              labelWidth: 30,
              labelTextStyle: {color: 'gray'},
              frontColor: '#177AD5',
            },
            {value: 30, frontColor: '#ED6665'},
            {
              value: 65,
              label: 'Aug',
              spacing: 2,
              labelWidth: 30,
              labelTextStyle: {color: 'gray'},
              frontColor: '#177AD5',
            },
            {value: 30, frontColor: '#ED6665'},
          ];
  
export {
    barData
}